# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
import numpy as np

In [5]:
# Create a rank 1 array
a = np.array([1, 2, 3])   

print(type(a))            
print(a.shape)           
print(a[0], a[1], a[2])   

# Change an element of the array
a[0] = 5                  
print(a)                  

# Create a rank 2 array
b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])  

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [4]:
# Create an array of all zeros
a = np.zeros((2,2))   
print(a)              

# Create an array of all ones
b = np.ones((1,2))    
print(b)              

# Create a constant array
c = np.full((2,2), 7)  
print(c)               

# Create a 2x2 identity matrix
d = np.eye(2)         
print(d)              

# Create an array filled with random values
e = np.random.random((2,2))  
print(e)       

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.23055208 0.86751014]
 [0.72169703 0.41217041]]
